name: chatme
description: "My chat App."
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_storage: ^12.4.5
  http: ^1.4.0
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  loading_animation_widget: ^1.3.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  random_string: ^2.3.1
  flutter_sound_record: ^3.3.2
  permission_handler: ^11.3.1
  just_audio: ^0.9.46
  animated_icon: ^0.0.9
  flutter_colorpicker: ^1.1.0
  cached_network_image: ^3.4.1
  sqflite: ^2.3.3+1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
      - asset/images/
  fonts:
  - family: Manrope
    fonts:
      - asset: asset/font/static/Manrope-Regular.ttf
        style: normal
